---
driver:
  name: azurerm

driver_config:
  subscription_id: <%= ENV['AZURE_SUBSCRIPTION_ID'] %>
  location: 'East US'
  machine_size: 'Standard_A1'

transport:
  ssh_key: '~/.ssh/ci_id_rsa'

platforms:
- name: ubuntu-14-04
  driver_config:
    image_urn: Canonical:UbuntuServer:14.04.5-LTS:latest
- name: ubuntu-16-04
  driver_config:
    image_urn: Canonical:UbuntuServer:16.04-LTS:latest
- name: centos-6
  driver_config:
    image_urn: OpenLogic:CentOS:6.9:latest
- name: centos-7
  driver_config:
    image_urn: OpenLogic:CentOS:7.4:latest
- name: oracle-6
  driver_config:
    image_urn: Oracle:Oracle-Linux:6.9:latest
- name: oracle-7
  driver_config:
    image_urn: Oracle:Oracle-Linux:7.4:latest
- name: rhel-6
  driver_config:
    image_urn: RedHat:RHEL:6.9:latest
- name: rhel-7
  driver_config:
    image_urn: RedHat:RHEL:7-RAW:latest
- name: debian-7
  driver_config:
    image_urn: credativ:Debian:7:latest
- name: debian-8
  driver_config:
    image_urn: credativ:Debian:8:latest
- name: opensuse-leap-42
  driver_config:
    image_urn: SUSE:openSUSE-Leap:42.3:latest
- name: sles-11
  driver_config:
    image_urn: SUSE:SLES:11-SP4:latest
- name: sles-12
  driver_config:
    image_urn: SSUSE:SLES:12-SP3:latest
